<div class="admin__field-group">
    <fieldset class="fieldset">
        <legend class="legend">Actions</legend>
        <div class="field">
            <label for="shipping_methods" class="label"><span>Shipping Methods</span></label>
            <div class="control">
                <select id="shipping_methods" name="shipping_methods[]" multiple>
                    <option value="method_1">Method 1</option>
                    <option value="method_2">Method 2</option>
                    <!-- Thêm các phương thức vận chuyển khác -->
                </select>
            </div>
        </div>
    </fieldset>
</div>
