<div class="admin__field-group">
    <fieldset class="fieldset">
        <legend class="legend">Conditions</legend>
        <div class="field">
            <label for="conditions" class="label"><span>Conditions</span></label>
            <div class="control">
                <!-- Tạo giao diện để nhập các điều kiện -->
                <textarea id="conditions" name="conditions" class="input-text" rows="5"></textarea>
            </div>
        </div>
    </fieldset>
</div>
